const colours = {
  colour1: {
    id: 1,
    usage: 'This is the primary colour. Used mainly in the logo and accents.',
    colourClass: 'primary',
    // colourTones: [this.state.colourTones],
    colourType: 'brand',
  },
  colour2: {
    id: 2,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'secondary1',
    // colourTones: [this.state.colourTones],
    colourType: 'brand',
  },
  colour3: {
    id: 3,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'secondary2',
    // colourTones: [this.state.colourTones],
    colourType: 'brand',
  },
  colour4: {
    id: 4,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'secondary3',
    // colourTones: [this.state.colourTones],
    colourType: 'brand',
  },
  colour5: {
    id: 5,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'black',
    // colourTones: [this.state.colourTones],
    colourType: 'neutral',
  },
  colour6: {
    id: 6,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'white',
    // colourTones: [this.state.colourTones],
    colourType: 'neutral',
  },
  colour7: {
    id: 7,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'pale-grey',
    // colourTones: [this.state.colourTones],
    colourType: 'neutral',
  },
  colour8: {
    id: 8,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'light-grey',
    // colourTones: [this.state.colourTones],
    colourType: 'neutral',
  },
  colour9: {
    id: 9,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'grey',
    // colourTones: [this.state.colourTones],
    colourType: 'neutral',
  },
  colour10: {
    id: 10,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'medium-grey',
    // colourTones: [this.state.colourTones],
    colourType: 'neutral',
  },
  colour11: {
    id: 11,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'dark-grey',
    // colourTones: [this.state.colourTones],
    colourType: 'neutral',
  },
  colour12: {
    id: 12,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'positive',
    // colourTones: [this.state.colourTones],
    colourType: 'utility',
  },
  colour13: {
    id: 13,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'caution',
    // colourTones: [this.state.colourTones],
    colourType: 'utility',
  },
  colour14: {
    id: 14,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'negative',
    // colourTones: [this.state.colourTones],
    colourType: 'utility',
  },
  colour16: {
    id: 15,
    usage: 'Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
    colourClass: 'info',
    // colourTones: [this.state.colourTones],
    colourType: 'utility',
  },
};

export default colours;
